server:
  port: 9999

debug: false
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/spring_boot?characterEncoding=utf8&useSSL=false&allowMultiQueries=true
  rabbitmq:
    username: guest
    password: guest
    addresses: localhost:5672
#    virtual-host: /
    connection-timeout: 10s

jwt:
  token:
    secret: characterEncoding
    expiration: 6000000
    isuser: zayan

logging:
  level:
    com.zayan.www.repository: debug

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml

netty:
  port: 7000
  url: 127.0.0.1

sale:
  admin: adminUserLoginSale

